### ISSUE TITLE
AWS ECS, ECR과 Docker를 통한 무중단 배포 환경 구축

### ISSUE THREAD

**Issue by D0ri123** [dnd-side-project/dnd-8th-1-backend#13]
## 📌Feature Issue
> AWS의 ECS, ECR을 통하여 Docker를 활용합니다.
## 📝To-do
- [x] Dockerfile 생성하여 Docker 이미지 빌드
- [x] ECR 생성 및 이미지 push
- [x] ECS 클러스터 및 테스크 생성
- [x] Fargate 생성
- [x] GIthub actions 설정
- [x] Rolling Update 배포
## ETC
>

**Comment by D0ri123** [comment]
Dockerfile 작성에 미숙하다고 판단하여 Github actions, Code deploy 그리고 Nginx를 사용하여 무중단 배포를 진행할 예정입니다.
