### ISSUE TITLE
프로필 등록 관련 피드백 반영 dto 개선

### ISSUE THREAD

**Issue by D0ri123** [dnd-side-project/dnd-8th-1-backend#161]
## 📌Feature Issue
> 프로필 등록 기능에 관련하여 응답 Dto에 대한 피드백을 반영하여 개선합니다.
## 📝To-do
- [x] dto 필드 중 profileName을 name으로 변경
- [x] twitter url 을 TikTok url로 변경
- [x] 프로필 유형 정보 추가
## ETC
> None
