### ISSUE TITLE
활동내역에서 사용자가 등록한 공연 조회

### ISSUE THREAD

**Issue by D0ri123** [dnd-side-project/dnd-8th-1-backend#172]
## 📌Feature Issue
> 사용자는 활동 내역에서 자신이 등록한 공연 정보글들을 조회할 수 있습니다.
## 📝To-do
- [x] 사용자가 등록한 공연 조회 컨트롤러 메서드 구현
- [x] 관련 순수, 복합 서비스 구현
- [x] security config에 url 추가
- [x] 관련 응답 dto를 swagger docs 에 매핑
## ETC
> None
