### ISSUE TITLE
aws parameter store 적용

### ISSUE THREAD

**Issue by soochangoforit** [dnd-side-project/dnd-8th-1-backend#28]
## 📌Feature Issue
> aws parameter store 적용
## 📝To-do
- [x] aws parameter store 적용
- [x] 내장 h2 database 적용
- [x] 내장 redis 적용
## ETC
> None
