### ISSUE TITLE
Github Actions 설정 추가

### ISSUE THREAD

**Issue by D0ri123** [dnd-side-project/dnd-8th-1-backend#5]
## 📌Feature Issue
> 무중단 배포를 위한 배포 환경 구축
## 📝To-do
- [x] 레포지터리와 Github Actions 연동
- [x] S3 생성
- [x] EC2 생성
- [x] AWS CodeDeploy 생성
- [x] CodeDeploy 스크립트 작성
## ETC
> no content
