### ISSUE TITLE
이벤트 상세 조회 기능 추가

### ISSUE THREAD

**Issue by soochangoforit** [dnd-side-project/dnd-8th-1-backend#50]
## 📌Feature Issue
> 이벤트 글을 상세 조회할 수 있다.
## 📝To-do
- [x] 이벤트 글 상세 조회
- [x] 상세 조회는 로그인 없이도 접근이 가능하다.
- [x] 상세 조회 기능 구현시 data jpa를 활용 하고자 한다.
## ETC
>None
