### ISSUE TITLE
이벤트 전체 조회 코드 수정

### ISSUE THREAD

**Issue by soochangoforit** [dnd-side-project/dnd-8th-1-backend#57]
## 📌Feature Issue
> 이벤트 전체 조회 코드 수정
## 📝To-do
- [x] 이벤트 전체 조회 시, 마감 기한 지난 것도 우선적으로 보여주기
- [x] 이벤트 전체 조회 시, 제일 최근에 올라온 게시글이 위에 위치하도록 정렬 조건 추가
- [x] 이벤트 전체 조회 시, 응답 값 변수명 명세서에 맞게 변경하기
- [x] 페이징 응답 시, 필요한 데이터만 응답 하도록 수정
## ETC
> None
