### ISSUE TITLE
공연 정보글 상세조회 기능 추가

### ISSUE THREAD

**Issue by D0ri123** [dnd-side-project/dnd-8th-1-backend#83]
## 📌Feature Issue
> 서비스 이용자 모두 공연 정보글을 상세조회할 수 있습니다.
## 📝To-do
- [x] Controller에 공연 정보 상세조회 메서드 추가
- [x] 공연정보 상세조회 관련 response Dto 추가
- [x] 상세조회 관련 service 추가
## ETC
> None
