### ISSUE TITLE
이벤트 글 삭제 기능 구현

### ISSUE THREAD

**Issue by D0ri123** [dnd-side-project/dnd-8th-1-backend#92]
## 📌Feature Issue
> 작성자는 이벤트글을 삭제할 수 있습니다.
## 📝To-do
- [x] 이벤트 컨트롤러에 삭제하는 메서드 추가
- [x] 이벤트 순수 서비스에서 삭제하는 서비스 메서드 추가
- [x] 삭제 관련 예외 처리
## ETC
> None
