### ISSUE TITLE
공연 전체 조회 코드 개선

### ISSUE THREAD

**Issue by soochangoforit** [dnd-side-project/dnd-8th-1-backend#97]
## 📌Feature Issue
> 공연 전체 조회 코드 개선
## 📝To-do
- [x] 공연 전체 조회 코드를 개선합니다.
- [x] countQuery 을 최적화 합니다.
- [x] PageDto를 통해서 페이지 네이션에 필요한 데이터만 반환합니다.
## ETC
> None
